import { Button } from "@/components/ui/button";
import { CheckCircle2, ClipboardCheck, Gauge, ShieldCheck, SlidersHorizontal, Stamp, Workflow } from "lucide-react";
import { useState } from "react";

type Tab = "general" | "approval" | "domain" | "identity";

export default function SystemConfigShell({ onOpenIdentity }: { onOpenIdentity: () => void }) {
  const [tab, setTab] = useState<Tab>("general");
  const items = [{ id: "general" as const, label: "通用设置", icon: SlidersHorizontal }, { id: "approval" as const, label: "审批配置", icon: ClipboardCheck }, { id: "domain" as const, label: "工作域配置", icon: Workflow }, { id: "identity" as const, label: "身份与权限", icon: ShieldCheck }];
  return <div className="min-h-[calc(100vh-56px)] bg-[#f5f7fb] p-4 sm:p-6"><div className="mx-auto grid max-w-6xl gap-4 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="rounded-lg border border-slate-200 bg-white p-2 shadow-sm"><div className="border-b border-slate-100 px-3 py-3"><p className="text-[10px] font-bold tracking-[.16em] text-[#5b72a8]">SYSTEM CONFIGURATION</p><h1 className="mt-1 text-base font-semibold text-slate-800">系统配置</h1></div><nav className="mt-2 grid gap-1">{items.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`flex items-center gap-2 rounded px-3 py-2.5 text-left text-sm ${tab === item.id ? "bg-[#eaf1ff] font-semibold text-[#245fc8]" : "text-slate-600 hover:bg-slate-50"}`}><item.icon size={16} />{item.label}</button>)}</nav></aside><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm">{tab === "general" && <GeneralSettings />}{tab === "approval" && <ApprovalSettings />}{tab === "domain" && <DomainSettings />}{tab === "identity" && <IdentitySettings onOpenIdentity={onOpenIdentity} />}</section></div></div>;
}

function GeneralSettings() { return <div><Header eyebrow="GENERAL SETTINGS" title="通用设置" description="恢复原始系统配置入口；系统级设置与项目运行规则将在后续版本由管理员持久化管理。" /><div className="mt-6 grid gap-4 md:grid-cols-2"><ConfigCard icon={Gauge} title="平台运行状态" value="内部账号认证已启用" description="会话采用 HttpOnly Cookie，账号由管理员统一管理。" /><ConfigCard icon={Stamp} title="系统水印" value="预览模式：未配置" description="水印内容与样式将作为系统级配置持久化。" /></div></div>; }
function ApprovalSettings() { return <div><Header eyebrow="APPROVAL CONFIGURATION" title="审批配置" description="项目流程已接入待审核、审核通过、审核驳回三个状态；审核通过后方可发布。" /><div className="mt-6 rounded-lg border border-[#cfe0ff] bg-[#f5f9ff] p-5"><div className="flex gap-3"><ClipboardCheck className="mt-0.5 text-[#2d6bea]" size={20} /><div><p className="font-semibold text-slate-800">项目流程发布审批</p><p className="mt-1 text-sm leading-6 text-slate-600">项目所有者或系统管理员可在流程设计中心完成审核。设计者可创建并编辑流程，但不能绕过审核直接发布。</p><div className="mt-3 flex items-center gap-2 text-xs text-emerald-700"><CheckCircle2 size={14} />当前规则已在服务端强制执行</div></div></div></div></div>; }
function DomainSettings() { return <div><Header eyebrow="WORK DOMAIN" title="工作域配置" description="业务项目作为当前工作域与数据隔离边界；项目角色决定流程查看、设计、运行和管理权限。" /><div className="mt-6 rounded-lg border border-slate-200 p-5"><div className="flex gap-3"><Workflow className="mt-0.5 text-[#2d6bea]" size={20} /><div><p className="font-semibold text-slate-800">项目工作域</p><p className="mt-1 text-sm leading-6 text-slate-600">每个业务项目独立维护成员、流程、仓库目录和审核上下文。临时项目角色到期后会自动失效，且不会赋予其他项目访问权。</p></div></div></div></div>; }
function IdentitySettings({ onOpenIdentity }: { onOpenIdentity: () => void }) { return <div><Header eyebrow="IDENTITY & AUTHORIZATION" title="身份与权限" description="系统用户、系统角色、流程角色、临时授权和授权审计均由内部 IAM 管理。" /><Button className="mt-6 bg-[#2d6bea] hover:bg-[#255bc8]" onClick={onOpenIdentity}><ShieldCheck size={16} />打开身份与权限中心</Button></div>; }
function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="border-b border-slate-100 pb-4"><p className="text-[11px] font-bold tracking-[.16em] text-[#5b72a8]">{eyebrow}</p><h2 className="mt-1 text-xl font-semibold text-slate-800">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>; }
function ConfigCard({ icon: Icon, title, value, description }: { icon: typeof Gauge; title: string; value: string; description: string }) { return <div className="rounded-lg border border-slate-200 p-4"><Icon size={18} className="text-[#2d6bea]" /><p className="mt-3 text-sm font-semibold text-slate-800">{title}</p><p className="mt-1 text-sm text-[#245fc8]">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p></div>; }
