import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import WorkflowCanvas from "@/components/WorkflowCanvas";
import { trpc } from "@/lib/trpc";
import { ArchiveRestore, ChevronDown, ChevronRight, Download, FileJson, FolderClosed, FolderOpen, FolderPlus, Image, MoreHorizontal, Search, Upload } from "lucide-react";
import { type ChangeEvent, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import type { ProjectRecord } from "./ProjectWorkspace";

type Folder = { id: string; parentId?: string | null; name: string; description?: string | null };
type WarehouseWorkflow = { id: string; name: string; description?: string | null; folderId?: string | null; flowType: string; status: string; auditStatus: string; definitionVersion: number };

function FlowBadge({ type }: { type: string }) {
  const styles: Record<string, string> = { state: "bg-blue-100 text-blue-700", control: "bg-violet-100 text-violet-700", data: "bg-emerald-100 text-emerald-700" };
  const labels: Record<string, string> = { state: "状态", control: "控制", data: "数据" };
  return <span className={`rounded px-1.5 py-0.5 text-[10px] ${styles[type] ?? "bg-slate-100 text-slate-600"}`}>{labels[type] ?? type}</span>;
}

export default function WorkflowWarehouse({ projects, onOpenWorkflow }: { projects: ProjectRecord[]; onOpenWorkflow: (project: ProjectRecord, workflowId: string) => void }) {
  const utils = trpc.useUtils();
  const [projectId, setProjectId] = useState("");
  const [selectedFolderId, setSelectedFolderId] = useState<string | null>(null);
  const [selectedWorkflowId, setSelectedWorkflowId] = useState<string | null>(null);
  const [checkedIds, setCheckedIds] = useState<string[]>([]);
  const [folderName, setFolderName] = useState("");
  const [keyword, setKeyword] = useState("");
  const [batchMenuOpen, setBatchMenuOpen] = useState(false);
  const importRef = useRef<HTMLInputElement>(null);
  const currentProject = projects.find(project => project.id === projectId) ?? projects[0] ?? null;
  const activeProjectId = currentProject?.id ?? "00000000";
  const warehouse = trpc.project.warehouse.useQuery({ projectId: activeProjectId }, { enabled: Boolean(currentProject) });
  const access = trpc.project.access.useQuery({ projectId: activeProjectId }, { enabled: Boolean(currentProject) });
  const workflowDetail: any = trpc.workflow.get.useQuery({ id: selectedWorkflowId ?? "00000000" }, { enabled: Boolean(selectedWorkflowId) });
  const exportInput = useMemo(() => ({ projectId: activeProjectId, workflowIds: checkedIds }), [activeProjectId, checkedIds]);
  const exportWorkflows = trpc.project.exportWorkflows.useQuery(exportInput, { enabled: false, retry: false });
  const canEdit = Boolean(access.data?.permissions?.has("project:workflow:edit"));
  const folders = (warehouse.data?.folders ?? []) as Folder[];
  const workflows = (warehouse.data?.workflows ?? []) as WarehouseWorkflow[];
  const selectedFolder = folders.find(folder => folder.id === selectedFolderId) ?? null;
  const scoped = selectedFolderId ? workflows.filter(workflow => workflow.folderId === selectedFolderId) : workflows.filter(workflow => !workflow.folderId);
  const visibleWorkflows = scoped.filter(workflow => `${workflow.name} ${workflow.description ?? ""} ${workflow.flowType}`.toLowerCase().includes(keyword.trim().toLowerCase()));
  const children = (parentId: string | null) => folders.filter(folder => (folder.parentId ?? null) === parentId);
  const invalidate = () => void utils.project.warehouse.invalidate({ projectId: activeProjectId });
  const createFolder = trpc.project.createFolder.useMutation({ onSuccess: () => { invalidate(); setFolderName(""); toast.success("仓库目录已创建。"); }, onError: error => toast.error(error.message) });
  const updateFolder = trpc.project.updateFolder.useMutation({ onSuccess: () => { invalidate(); toast.success("目录说明已更新。"); }, onError: error => toast.error(error.message) });
  const deleteFolder = trpc.project.deleteFolder.useMutation({ onSuccess: () => { invalidate(); setSelectedFolderId(null); toast.success("空目录已删除。"); }, onError: error => toast.error(error.message) });
  const moveWorkflow = trpc.project.moveWorkflow.useMutation({ onSuccess: () => { invalidate(); toast.success("流程已移动至目标目录。"); }, onError: error => toast.error(error.message) });
  const createWorkflow = trpc.project.createWorkflow.useMutation({ onSuccess: () => { invalidate(); toast.success("流程已导入并处于待审核状态。"); }, onError: error => toast.error(error.message) });

  const download = (name: string, payload: unknown) => { const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(blob); anchor.download = name; anchor.click(); URL.revokeObjectURL(anchor.href); };
  const exportSelected = async () => { if (!checkedIds.length) return toast.error("请至少勾选一个流程后导出。"); const result = await exportWorkflows.refetch(); if (result.error) return toast.error(result.error.message); download(`${currentProject?.code ?? "workflow"}-仓库导出.json`, { exportedAt: new Date().toISOString(), project: { code: currentProject?.code, name: currentProject?.name }, workflows: result.data }); toast.success(`已导出 ${result.data?.length ?? 0} 个流程。`); setBatchMenuOpen(false); };
  const importFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !currentProject) return; try { const parsed = JSON.parse(await file.text()); const items = Array.isArray(parsed.workflows) ? parsed.workflows : [parsed.workflow ?? parsed]; for (const item of items) { const definition = item.definition ?? item.workflow?.definition; if (!definition?.nodes || !definition?.edges) throw new Error("导入文件缺少流程定义。"); await createWorkflow.mutateAsync({ projectId: currentProject.id, name: String(item.name ?? item.workflow?.name ?? "导入流程"), description: typeof item.description === "string" ? item.description : undefined, flowType: ["state", "control", "data"].includes(item.flowType) ? item.flowType : "state", folderId: selectedFolderId, definition }); } } catch (error) { toast.error(error instanceof Error ? error.message : "导入文件不是有效的流程仓库 JSON。"); } finally { event.target.value = ""; } };

  if (!currentProject) return <div className="min-h-[calc(100vh-56px)] bg-[#f5f7fb] p-4 sm:p-6"><div className="grid min-h-80 place-items-center rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">暂无可访问项目；请先在流程设计中创建或加入一个业务项目。</div></div>;

  return <div className="min-h-[calc(100vh-56px)] bg-[#f5f7fb] p-4 sm:p-6"><div className="mx-auto max-w-[1500px]"><div className="mb-4 flex flex-col gap-3 border-b border-slate-200 pb-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold tracking-[.16em] text-[#5b72a8]">PROCESS WAREHOUSE</p><h1 className="mt-1 text-xl font-semibold text-slate-800">流程仓库</h1><p className="mt-1 text-sm text-slate-500">在项目目录树中检索、归档、预览、批量导入和导出状态、控制与数据流程。</p></div><select className="h-9 min-w-48 rounded-md border border-slate-200 bg-white px-2 text-sm" value={currentProject.id} onChange={event => { setProjectId(event.target.value); setSelectedFolderId(null); setSelectedWorkflowId(null); setCheckedIds([]); setKeyword(""); }}>{projects.map(project => <option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select></div>
    <div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)_430px]"><aside className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-3"><p className="text-sm font-semibold text-slate-700">流程列表</p><div className="mt-3 flex gap-2"><div className="relative min-w-0 flex-1"><Search size={14} className="absolute left-2.5 top-2.5 text-slate-400" /><Input className="h-9 pl-8 text-xs" placeholder="请输入搜索内容" value={keyword} onChange={event => setKeyword(event.target.value)} /></div><div className="relative"><Button type="button" size="icon" className="h-9 w-9" title="批量操作" disabled={!canEdit} onClick={() => setBatchMenuOpen(value => !value)}><MoreHorizontal size={16} /></Button>{batchMenuOpen && <div className="absolute right-0 z-20 mt-1 w-32 rounded-md border border-slate-200 bg-white p-1 shadow-lg"><button type="button" className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-xs hover:bg-slate-50" onClick={() => importRef.current?.click()}><Upload size={13} />批量导入</button><button type="button" className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-xs hover:bg-slate-50 disabled:cursor-not-allowed disabled:text-slate-300" disabled={!checkedIds.length} onClick={() => void exportSelected()}><Download size={13} />批量导出</button></div>}</div></div>{canEdit && <form className="mt-2 flex gap-2" onSubmit={event => { event.preventDefault(); if (folderName.trim()) createFolder.mutate({ projectId: activeProjectId, name: folderName.trim(), parentId: selectedFolderId }); }}><Input className="h-8 text-xs" placeholder={selectedFolderId ? "新增子目录" : "新增根目录"} value={folderName} onChange={event => setFolderName(event.target.value)} /><Button className="h-8 px-2" type="submit"><FolderPlus size={14} /></Button></form>}</div><div className="max-h-[620px] overflow-y-auto p-2"><button className={`flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm ${!selectedFolderId ? "bg-[#eaf1ff] text-[#245fc8]" : "text-slate-600 hover:bg-slate-50"}`} onClick={() => setSelectedFolderId(null)}><ArchiveRestore size={15} />根目录 <span className="ml-auto text-xs text-slate-400">{workflows.filter(workflow => !workflow.folderId).length}</span></button>{children(null).map(folder => <FolderTree key={folder.id} folder={folder} level={0} childrenOf={children} selectedId={selectedFolderId} onSelect={setSelectedFolderId} />)}</div></aside>
      <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-100 p-3"><div><p className="text-sm font-semibold text-slate-700">{selectedFolder?.name ?? "根目录流程"}</p><p className="mt-1 text-[11px] text-slate-400">勾选流程后可批量导出；选择一条流程在右侧查看简介和只读画布。</p></div>{selectedFolderId && canEdit && <div className="flex gap-3"><button type="button" className="text-xs text-[#2d6bea] hover:underline" onClick={() => { const description = window.prompt("目录说明", selectedFolder?.description ?? ""); if (description !== null && selectedFolder) updateFolder.mutate({ projectId: activeProjectId, folderId: selectedFolder.id, description }); }}>编辑简介</button><button type="button" className="text-xs text-red-600 hover:underline" onClick={() => deleteFolder.mutate({ projectId: activeProjectId, folderId: selectedFolderId })}>删除目录</button></div>}</div><div className="divide-y divide-slate-100">{visibleWorkflows.map(workflow => <div key={workflow.id} className={`flex items-center gap-3 p-3 transition-colors ${selectedWorkflowId === workflow.id ? "bg-blue-50" : "hover:bg-slate-50"}`}><input type="checkbox" aria-label={`选择${workflow.name}`} checked={checkedIds.includes(workflow.id)} onChange={() => setCheckedIds(current => current.includes(workflow.id) ? current.filter(id => id !== workflow.id) : current.concat(workflow.id))} /><button className="min-w-0 flex-1 text-left" onClick={() => setSelectedWorkflowId(workflow.id)}><div className="flex items-center gap-2"><FileJson size={15} className="text-[#2d6bea]" /><p className="truncate text-sm font-medium text-slate-800">{workflow.name}</p><FlowBadge type={workflow.flowType} /></div><p className="mt-1 truncate text-xs text-slate-400">{workflow.description || "未填写流程简介"} · v{workflow.definitionVersion}</p></button>{canEdit && <select aria-label="移动流程目录" className="h-7 max-w-28 rounded border border-slate-200 bg-white px-1 text-[11px]" value={workflow.folderId ?? ""} onChange={event => moveWorkflow.mutate({ projectId: activeProjectId, workflowId: workflow.id, folderId: event.target.value || null })}><option value="">根目录</option>{folders.map(folder => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select>}</div>)}{!visibleWorkflows.length && <div className="grid min-h-64 place-items-center p-8 text-center"><div><FolderClosed className="mx-auto text-slate-300" size={30} /><p className="mt-3 text-sm text-slate-400">{keyword ? "没有搜到任何数据" : "该目录暂无流程。"}</p></div></div>}</div></section>
      <aside className="min-w-0 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-3"><p className="text-sm font-semibold text-slate-700">流程简介</p><span className="text-[11px] text-slate-400">流程图</span></div>{workflowDetail.data ? <div><div className="border-b border-slate-100 p-3"><div className="flex items-center gap-2"><p className="min-w-0 flex-1 truncate text-sm font-semibold text-slate-800">{workflowDetail.data.name}</p><FlowBadge type={workflowDetail.data.flowType} /></div><p className="mt-2 text-xs leading-5 text-slate-500">{workflowDetail.data.description || "未填写流程简介"}</p><div className="mt-3 flex flex-wrap gap-2"><Button className="h-7 text-xs" size="sm" onClick={() => onOpenWorkflow(currentProject, workflowDetail.data.id)}>打开设计器</Button><span className="inline-flex h-7 items-center gap-1 rounded border border-slate-200 px-2 text-[11px] text-slate-500"><Image size={12} />全屏与图片工具位于预览画布</span></div></div><div className="h-[470px]"><WorkflowCanvas workflowId={workflowDetail.data.id} definition={workflowDetail.data.definition} readOnly /></div></div> : <div className="grid h-[560px] place-items-center p-8 text-center text-sm leading-6 text-slate-400"><div><FolderClosed className="mx-auto text-slate-300" size={30} /><p className="mt-3">从中间列表选择一条流程，查看流程简介、版本信息与只读流程图。</p></div></div>}</aside></div><input ref={importRef} type="file" accept="application/json,.json" className="hidden" onChange={importFile} /></div></div>;
}

function FolderTree({ folder, level, childrenOf, selectedId, onSelect }: { folder: Folder; level: number; childrenOf: (id: string | null) => Folder[]; selectedId: string | null; onSelect: (id: string) => void }) {
  const [expanded, setExpanded] = useState(true);
  const children = childrenOf(folder.id);
  return <div><button className={`flex w-full items-center gap-1 rounded px-2 py-1.5 text-left text-sm ${selectedId === folder.id ? "bg-[#eaf1ff] text-[#245fc8]" : "text-slate-600 hover:bg-slate-50"}`} style={{ paddingLeft: `${8 + level * 16}px` }} onClick={() => onSelect(folder.id)}>{children.length ? <span onClick={event => { event.stopPropagation(); setExpanded(value => !value); }}>{expanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</span> : <span className="w-3.5" />}{expanded ? <FolderOpen size={15} /> : <FolderClosed size={15} />}<span className="truncate">{folder.name}</span></button>{expanded && children.map(child => <FolderTree key={child.id} folder={child} level={level + 1} childrenOf={childrenOf} selectedId={selectedId} onSelect={onSelect} />)}</div>;
}
